services:
  postgres:
    image: postgres:16
    container_name: firin-postgres
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: firin_db
      POSTGRES_USER: firin_user
      POSTGRES_PASSWORD: firin123
    volumes:
      - firin_postgres_data:/var/lib/postgresql/data

volumes:
  firin_postgres_data:
